//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.10.25 at 09:51:33 AM EDT 
//


package com.solacesystems.semp_jaxb.r9_2_0VMR.reply;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for clientQueueType complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="clientQueueType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="queue-priority" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="length-msgs" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="length-work" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="high-water-mark-work" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="max-work" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="discards-msgs" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="delivered-msgs" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "clientQueueType", propOrder = {

})
public class ClientQueueType {

    @XmlElement(name = "queue-priority", required = true)
    protected String queuePriority;
    @XmlElement(name = "length-msgs")
    protected long lengthMsgs;
    @XmlElement(name = "length-work")
    protected long lengthWork;
    @XmlElement(name = "high-water-mark-work")
    protected long highWaterMarkWork;
    @XmlElement(name = "max-work")
    protected long maxWork;
    @XmlElement(name = "discards-msgs")
    protected long discardsMsgs;
    @XmlElement(name = "delivered-msgs")
    protected long deliveredMsgs;

    /**
     * Gets the value of the queuePriority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQueuePriority() {
        return queuePriority;
    }

    /**
     * Sets the value of the queuePriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQueuePriority(String value) {
        this.queuePriority = value;
    }

    /**
     * Gets the value of the lengthMsgs property.
     * 
     */
    public long getLengthMsgs() {
        return lengthMsgs;
    }

    /**
     * Sets the value of the lengthMsgs property.
     * 
     */
    public void setLengthMsgs(long value) {
        this.lengthMsgs = value;
    }

    /**
     * Gets the value of the lengthWork property.
     * 
     */
    public long getLengthWork() {
        return lengthWork;
    }

    /**
     * Sets the value of the lengthWork property.
     * 
     */
    public void setLengthWork(long value) {
        this.lengthWork = value;
    }

    /**
     * Gets the value of the highWaterMarkWork property.
     * 
     */
    public long getHighWaterMarkWork() {
        return highWaterMarkWork;
    }

    /**
     * Sets the value of the highWaterMarkWork property.
     * 
     */
    public void setHighWaterMarkWork(long value) {
        this.highWaterMarkWork = value;
    }

    /**
     * Gets the value of the maxWork property.
     * 
     */
    public long getMaxWork() {
        return maxWork;
    }

    /**
     * Sets the value of the maxWork property.
     * 
     */
    public void setMaxWork(long value) {
        this.maxWork = value;
    }

    /**
     * Gets the value of the discardsMsgs property.
     * 
     */
    public long getDiscardsMsgs() {
        return discardsMsgs;
    }

    /**
     * Sets the value of the discardsMsgs property.
     * 
     */
    public void setDiscardsMsgs(long value) {
        this.discardsMsgs = value;
    }

    /**
     * Gets the value of the deliveredMsgs property.
     * 
     */
    public long getDeliveredMsgs() {
        return deliveredMsgs;
    }

    /**
     * Sets the value of the deliveredMsgs property.
     * 
     */
    public void setDeliveredMsgs(long value) {
        this.deliveredMsgs = value;
    }

}
