//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.10.25 at 09:51:33 AM EDT 
//


package com.solacesystems.semp_jaxb.r9_2_0VMR.reply;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for event-thresholds complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="event-thresholds"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="set-value" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/&gt;
 *         &lt;element name="clear-value" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/&gt;
 *         &lt;element name="set-value-float" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *         &lt;element name="clear-value-float" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *         &lt;element name="set-percentage" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *         &lt;element name="clear-percentage" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "event-thresholds", propOrder = {

})
public class EventThresholds {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(name = "set-value")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger setValue;
    @XmlElement(name = "clear-value")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger clearValue;
    @XmlElement(name = "set-value-float")
    protected Float setValueFloat;
    @XmlElement(name = "clear-value-float")
    protected Float clearValueFloat;
    @XmlElement(name = "set-percentage")
    @XmlSchemaType(name = "unsignedInt")
    protected Long setPercentage;
    @XmlElement(name = "clear-percentage")
    @XmlSchemaType(name = "unsignedInt")
    protected Long clearPercentage;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the setValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSetValue() {
        return setValue;
    }

    /**
     * Sets the value of the setValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSetValue(BigInteger value) {
        this.setValue = value;
    }

    /**
     * Gets the value of the clearValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getClearValue() {
        return clearValue;
    }

    /**
     * Sets the value of the clearValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setClearValue(BigInteger value) {
        this.clearValue = value;
    }

    /**
     * Gets the value of the setValueFloat property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getSetValueFloat() {
        return setValueFloat;
    }

    /**
     * Sets the value of the setValueFloat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setSetValueFloat(Float value) {
        this.setValueFloat = value;
    }

    /**
     * Gets the value of the clearValueFloat property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getClearValueFloat() {
        return clearValueFloat;
    }

    /**
     * Sets the value of the clearValueFloat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setClearValueFloat(Float value) {
        this.clearValueFloat = value;
    }

    /**
     * Gets the value of the setPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSetPercentage() {
        return setPercentage;
    }

    /**
     * Sets the value of the setPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSetPercentage(Long value) {
        this.setPercentage = value;
    }

    /**
     * Gets the value of the clearPercentage property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getClearPercentage() {
        return clearPercentage;
    }

    /**
     * Sets the value of the clearPercentage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setClearPercentage(Long value) {
        this.clearPercentage = value;
    }

}
