//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.10.25 at 09:51:33 AM EDT 
//


package com.solacesystems.semp_jaxb.r9_2_0VMR.reply;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for qendpt-data-rates complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="qendpt-data-rates"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="current-ingress-byte-rate-per-second" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="current-ingress-rate-per-second" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="current-egress-byte-rate-per-second" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="current-egress-rate-per-second" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="average-ingress-byte-rate-per-minute" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="average-ingress-rate-per-minute" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="average-egress-byte-rate-per-minute" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="average-egress-rate-per-minute" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "qendpt-data-rates", propOrder = {
    "currentIngressByteRatePerSecond",
    "currentIngressRatePerSecond",
    "currentEgressByteRatePerSecond",
    "currentEgressRatePerSecond",
    "averageIngressByteRatePerMinute",
    "averageIngressRatePerMinute",
    "averageEgressByteRatePerMinute",
    "averageEgressRatePerMinute"
})
public class QendptDataRates {

    @XmlElement(name = "current-ingress-byte-rate-per-second")
    protected long currentIngressByteRatePerSecond;
    @XmlElement(name = "current-ingress-rate-per-second")
    protected long currentIngressRatePerSecond;
    @XmlElement(name = "current-egress-byte-rate-per-second")
    protected long currentEgressByteRatePerSecond;
    @XmlElement(name = "current-egress-rate-per-second")
    protected long currentEgressRatePerSecond;
    @XmlElement(name = "average-ingress-byte-rate-per-minute")
    protected long averageIngressByteRatePerMinute;
    @XmlElement(name = "average-ingress-rate-per-minute")
    protected long averageIngressRatePerMinute;
    @XmlElement(name = "average-egress-byte-rate-per-minute")
    protected long averageEgressByteRatePerMinute;
    @XmlElement(name = "average-egress-rate-per-minute")
    protected long averageEgressRatePerMinute;

    /**
     * Gets the value of the currentIngressByteRatePerSecond property.
     * 
     */
    public long getCurrentIngressByteRatePerSecond() {
        return currentIngressByteRatePerSecond;
    }

    /**
     * Sets the value of the currentIngressByteRatePerSecond property.
     * 
     */
    public void setCurrentIngressByteRatePerSecond(long value) {
        this.currentIngressByteRatePerSecond = value;
    }

    /**
     * Gets the value of the currentIngressRatePerSecond property.
     * 
     */
    public long getCurrentIngressRatePerSecond() {
        return currentIngressRatePerSecond;
    }

    /**
     * Sets the value of the currentIngressRatePerSecond property.
     * 
     */
    public void setCurrentIngressRatePerSecond(long value) {
        this.currentIngressRatePerSecond = value;
    }

    /**
     * Gets the value of the currentEgressByteRatePerSecond property.
     * 
     */
    public long getCurrentEgressByteRatePerSecond() {
        return currentEgressByteRatePerSecond;
    }

    /**
     * Sets the value of the currentEgressByteRatePerSecond property.
     * 
     */
    public void setCurrentEgressByteRatePerSecond(long value) {
        this.currentEgressByteRatePerSecond = value;
    }

    /**
     * Gets the value of the currentEgressRatePerSecond property.
     * 
     */
    public long getCurrentEgressRatePerSecond() {
        return currentEgressRatePerSecond;
    }

    /**
     * Sets the value of the currentEgressRatePerSecond property.
     * 
     */
    public void setCurrentEgressRatePerSecond(long value) {
        this.currentEgressRatePerSecond = value;
    }

    /**
     * Gets the value of the averageIngressByteRatePerMinute property.
     * 
     */
    public long getAverageIngressByteRatePerMinute() {
        return averageIngressByteRatePerMinute;
    }

    /**
     * Sets the value of the averageIngressByteRatePerMinute property.
     * 
     */
    public void setAverageIngressByteRatePerMinute(long value) {
        this.averageIngressByteRatePerMinute = value;
    }

    /**
     * Gets the value of the averageIngressRatePerMinute property.
     * 
     */
    public long getAverageIngressRatePerMinute() {
        return averageIngressRatePerMinute;
    }

    /**
     * Sets the value of the averageIngressRatePerMinute property.
     * 
     */
    public void setAverageIngressRatePerMinute(long value) {
        this.averageIngressRatePerMinute = value;
    }

    /**
     * Gets the value of the averageEgressByteRatePerMinute property.
     * 
     */
    public long getAverageEgressByteRatePerMinute() {
        return averageEgressByteRatePerMinute;
    }

    /**
     * Sets the value of the averageEgressByteRatePerMinute property.
     * 
     */
    public void setAverageEgressByteRatePerMinute(long value) {
        this.averageEgressByteRatePerMinute = value;
    }

    /**
     * Gets the value of the averageEgressRatePerMinute property.
     * 
     */
    public long getAverageEgressRatePerMinute() {
        return averageEgressRatePerMinute;
    }

    /**
     * Sets the value of the averageEgressRatePerMinute property.
     * 
     */
    public void setAverageEgressRatePerMinute(long value) {
        this.averageEgressRatePerMinute = value;
    }

}
