//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.10.25 at 09:51:33 AM EDT 
//


package com.solacesystems.semp_jaxb.r9_2_0VMR.reply;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for replay-state complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="replay-state"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="replay-state" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="last-replayed-message-sent-time" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="last-replayed-message-sent-time-seconds" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="last-replay-start-time" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="last-replay-start-time-seconds" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="last-replay-complete-time" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="last-replay-complete-time-seconds" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="last-replay-failure-time" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="last-replay-failure-time-seconds" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="last-replay-failure-reason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "replay-state", propOrder = {
    "replayState",
    "lastReplayedMessageSentTime",
    "lastReplayedMessageSentTimeSeconds",
    "lastReplayStartTime",
    "lastReplayStartTimeSeconds",
    "lastReplayCompleteTime",
    "lastReplayCompleteTimeSeconds",
    "lastReplayFailureTime",
    "lastReplayFailureTimeSeconds",
    "lastReplayFailureReason"
})
public class ReplayState {

    @XmlElement(name = "replay-state")
    protected String replayState;
    @XmlElement(name = "last-replayed-message-sent-time")
    protected String lastReplayedMessageSentTime;
    @XmlElement(name = "last-replayed-message-sent-time-seconds")
    protected Integer lastReplayedMessageSentTimeSeconds;
    @XmlElement(name = "last-replay-start-time")
    protected String lastReplayStartTime;
    @XmlElement(name = "last-replay-start-time-seconds")
    protected Integer lastReplayStartTimeSeconds;
    @XmlElement(name = "last-replay-complete-time")
    protected String lastReplayCompleteTime;
    @XmlElement(name = "last-replay-complete-time-seconds")
    protected Integer lastReplayCompleteTimeSeconds;
    @XmlElement(name = "last-replay-failure-time")
    protected String lastReplayFailureTime;
    @XmlElement(name = "last-replay-failure-time-seconds")
    protected Integer lastReplayFailureTimeSeconds;
    @XmlElement(name = "last-replay-failure-reason")
    protected String lastReplayFailureReason;

    /**
     * Gets the value of the replayState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplayState() {
        return replayState;
    }

    /**
     * Sets the value of the replayState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplayState(String value) {
        this.replayState = value;
    }

    /**
     * Gets the value of the lastReplayedMessageSentTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastReplayedMessageSentTime() {
        return lastReplayedMessageSentTime;
    }

    /**
     * Sets the value of the lastReplayedMessageSentTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastReplayedMessageSentTime(String value) {
        this.lastReplayedMessageSentTime = value;
    }

    /**
     * Gets the value of the lastReplayedMessageSentTimeSeconds property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLastReplayedMessageSentTimeSeconds() {
        return lastReplayedMessageSentTimeSeconds;
    }

    /**
     * Sets the value of the lastReplayedMessageSentTimeSeconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLastReplayedMessageSentTimeSeconds(Integer value) {
        this.lastReplayedMessageSentTimeSeconds = value;
    }

    /**
     * Gets the value of the lastReplayStartTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastReplayStartTime() {
        return lastReplayStartTime;
    }

    /**
     * Sets the value of the lastReplayStartTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastReplayStartTime(String value) {
        this.lastReplayStartTime = value;
    }

    /**
     * Gets the value of the lastReplayStartTimeSeconds property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLastReplayStartTimeSeconds() {
        return lastReplayStartTimeSeconds;
    }

    /**
     * Sets the value of the lastReplayStartTimeSeconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLastReplayStartTimeSeconds(Integer value) {
        this.lastReplayStartTimeSeconds = value;
    }

    /**
     * Gets the value of the lastReplayCompleteTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastReplayCompleteTime() {
        return lastReplayCompleteTime;
    }

    /**
     * Sets the value of the lastReplayCompleteTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastReplayCompleteTime(String value) {
        this.lastReplayCompleteTime = value;
    }

    /**
     * Gets the value of the lastReplayCompleteTimeSeconds property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLastReplayCompleteTimeSeconds() {
        return lastReplayCompleteTimeSeconds;
    }

    /**
     * Sets the value of the lastReplayCompleteTimeSeconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLastReplayCompleteTimeSeconds(Integer value) {
        this.lastReplayCompleteTimeSeconds = value;
    }

    /**
     * Gets the value of the lastReplayFailureTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastReplayFailureTime() {
        return lastReplayFailureTime;
    }

    /**
     * Sets the value of the lastReplayFailureTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastReplayFailureTime(String value) {
        this.lastReplayFailureTime = value;
    }

    /**
     * Gets the value of the lastReplayFailureTimeSeconds property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLastReplayFailureTimeSeconds() {
        return lastReplayFailureTimeSeconds;
    }

    /**
     * Sets the value of the lastReplayFailureTimeSeconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLastReplayFailureTimeSeconds(Integer value) {
        this.lastReplayFailureTimeSeconds = value;
    }

    /**
     * Gets the value of the lastReplayFailureReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastReplayFailureReason() {
        return lastReplayFailureReason;
    }

    /**
     * Sets the value of the lastReplayFailureReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastReplayFailureReason(String value) {
        this.lastReplayFailureReason = value;
    }

}
