//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.10.25 at 09:51:33 AM EDT 
//


package com.solacesystems.semp_jaxb.r9_2_0VMR.reply;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for replay-stats complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="replay-stats"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="replays-initiated" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/&gt;
 *         &lt;element name="replays-succeeded" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/&gt;
 *         &lt;element name="replays-failed" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/&gt;
 *         &lt;element name="replayed-messages-sent" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/&gt;
 *         &lt;element name="replayed-messages-acked" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "replay-stats", propOrder = {

})
public class ReplayStats {

    @XmlElement(name = "replays-initiated", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger replaysInitiated;
    @XmlElement(name = "replays-succeeded", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger replaysSucceeded;
    @XmlElement(name = "replays-failed", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger replaysFailed;
    @XmlElement(name = "replayed-messages-sent", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger replayedMessagesSent;
    @XmlElement(name = "replayed-messages-acked", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger replayedMessagesAcked;

    /**
     * Gets the value of the replaysInitiated property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getReplaysInitiated() {
        return replaysInitiated;
    }

    /**
     * Sets the value of the replaysInitiated property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setReplaysInitiated(BigInteger value) {
        this.replaysInitiated = value;
    }

    /**
     * Gets the value of the replaysSucceeded property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getReplaysSucceeded() {
        return replaysSucceeded;
    }

    /**
     * Sets the value of the replaysSucceeded property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setReplaysSucceeded(BigInteger value) {
        this.replaysSucceeded = value;
    }

    /**
     * Gets the value of the replaysFailed property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getReplaysFailed() {
        return replaysFailed;
    }

    /**
     * Sets the value of the replaysFailed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setReplaysFailed(BigInteger value) {
        this.replaysFailed = value;
    }

    /**
     * Gets the value of the replayedMessagesSent property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getReplayedMessagesSent() {
        return replayedMessagesSent;
    }

    /**
     * Sets the value of the replayedMessagesSent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setReplayedMessagesSent(BigInteger value) {
        this.replayedMessagesSent = value;
    }

    /**
     * Gets the value of the replayedMessagesAcked property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getReplayedMessagesAcked() {
        return replayedMessagesAcked;
    }

    /**
     * Sets the value of the replayedMessagesAcked property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setReplayedMessagesAcked(BigInteger value) {
        this.replayedMessagesAcked = value;
    }

}
