//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.10.25 at 09:51:33 AM EDT 
//


package com.solacesystems.semp_jaxb.r9_2_0VMR.reply;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for revocation-check-common-stats-type complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="revocation-check-common-stats-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="crl"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;all&gt;
 *                   &lt;element name="valid" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/&gt;
 *                   &lt;element name="revoked" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/&gt;
 *                   &lt;element name="unknown" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/&gt;
 *                 &lt;/all&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ocsp"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;all&gt;
 *                   &lt;element name="valid" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/&gt;
 *                   &lt;element name="revoked" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/&gt;
 *                   &lt;element name="unknown" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/&gt;
 *                 &lt;/all&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ocsp-fallback-to-crl" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "revocation-check-common-stats-type", propOrder = {

})
public class RevocationCheckCommonStatsType {

    @XmlElement(required = true)
    protected RevocationCheckCommonStatsType.Crl crl;
    @XmlElement(required = true)
    protected RevocationCheckCommonStatsType.Ocsp ocsp;
    @XmlElement(name = "ocsp-fallback-to-crl")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger ocspFallbackToCrl;

    /**
     * Gets the value of the crl property.
     * 
     * @return
     *     possible object is
     *     {@link RevocationCheckCommonStatsType.Crl }
     *     
     */
    public RevocationCheckCommonStatsType.Crl getCrl() {
        return crl;
    }

    /**
     * Sets the value of the crl property.
     * 
     * @param value
     *     allowed object is
     *     {@link RevocationCheckCommonStatsType.Crl }
     *     
     */
    public void setCrl(RevocationCheckCommonStatsType.Crl value) {
        this.crl = value;
    }

    /**
     * Gets the value of the ocsp property.
     * 
     * @return
     *     possible object is
     *     {@link RevocationCheckCommonStatsType.Ocsp }
     *     
     */
    public RevocationCheckCommonStatsType.Ocsp getOcsp() {
        return ocsp;
    }

    /**
     * Sets the value of the ocsp property.
     * 
     * @param value
     *     allowed object is
     *     {@link RevocationCheckCommonStatsType.Ocsp }
     *     
     */
    public void setOcsp(RevocationCheckCommonStatsType.Ocsp value) {
        this.ocsp = value;
    }

    /**
     * Gets the value of the ocspFallbackToCrl property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOcspFallbackToCrl() {
        return ocspFallbackToCrl;
    }

    /**
     * Sets the value of the ocspFallbackToCrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOcspFallbackToCrl(BigInteger value) {
        this.ocspFallbackToCrl = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;all&gt;
     *         &lt;element name="valid" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/&gt;
     *         &lt;element name="revoked" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/&gt;
     *         &lt;element name="unknown" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/&gt;
     *       &lt;/all&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Crl {

        @XmlElement(required = true)
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger valid;
        @XmlElement(required = true)
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger revoked;
        @XmlElement(required = true)
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger unknown;

        /**
         * Gets the value of the valid property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getValid() {
            return valid;
        }

        /**
         * Sets the value of the valid property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setValid(BigInteger value) {
            this.valid = value;
        }

        /**
         * Gets the value of the revoked property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getRevoked() {
            return revoked;
        }

        /**
         * Sets the value of the revoked property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setRevoked(BigInteger value) {
            this.revoked = value;
        }

        /**
         * Gets the value of the unknown property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getUnknown() {
            return unknown;
        }

        /**
         * Sets the value of the unknown property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setUnknown(BigInteger value) {
            this.unknown = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;all&gt;
     *         &lt;element name="valid" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/&gt;
     *         &lt;element name="revoked" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/&gt;
     *         &lt;element name="unknown" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/&gt;
     *       &lt;/all&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Ocsp {

        @XmlElement(required = true)
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger valid;
        @XmlElement(required = true)
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger revoked;
        @XmlElement(required = true)
        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger unknown;

        /**
         * Gets the value of the valid property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getValid() {
            return valid;
        }

        /**
         * Sets the value of the valid property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setValid(BigInteger value) {
            this.valid = value;
        }

        /**
         * Gets the value of the revoked property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getRevoked() {
            return revoked;
        }

        /**
         * Sets the value of the revoked property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setRevoked(BigInteger value) {
            this.revoked = value;
        }

        /**
         * Gets the value of the unknown property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getUnknown() {
            return unknown;
        }

        /**
         * Sets the value of the unknown property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setUnknown(BigInteger value) {
            this.unknown = value;
        }

    }

}
