//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.10.25 at 09:51:33 AM EDT 
//


package com.solacesystems.semp_jaxb.r9_2_0VMR.reply;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for selector-stats-type complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="selector-stats-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="last-message-id-examined" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/&gt;
 *         &lt;element name="messages-selector-matched" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/&gt;
 *         &lt;element name="messages-selector-did-not-match" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/&gt;
 *         &lt;element name="total-messages-examined" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "selector-stats-type", propOrder = {
    "lastMessageIdExamined",
    "messagesSelectorMatched",
    "messagesSelectorDidNotMatch",
    "totalMessagesExamined"
})
public class SelectorStatsType {

    @XmlElement(name = "last-message-id-examined", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger lastMessageIdExamined;
    @XmlElement(name = "messages-selector-matched", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger messagesSelectorMatched;
    @XmlElement(name = "messages-selector-did-not-match", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger messagesSelectorDidNotMatch;
    @XmlElement(name = "total-messages-examined", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger totalMessagesExamined;

    /**
     * Gets the value of the lastMessageIdExamined property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLastMessageIdExamined() {
        return lastMessageIdExamined;
    }

    /**
     * Sets the value of the lastMessageIdExamined property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLastMessageIdExamined(BigInteger value) {
        this.lastMessageIdExamined = value;
    }

    /**
     * Gets the value of the messagesSelectorMatched property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMessagesSelectorMatched() {
        return messagesSelectorMatched;
    }

    /**
     * Sets the value of the messagesSelectorMatched property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMessagesSelectorMatched(BigInteger value) {
        this.messagesSelectorMatched = value;
    }

    /**
     * Gets the value of the messagesSelectorDidNotMatch property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMessagesSelectorDidNotMatch() {
        return messagesSelectorDidNotMatch;
    }

    /**
     * Sets the value of the messagesSelectorDidNotMatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMessagesSelectorDidNotMatch(BigInteger value) {
        this.messagesSelectorDidNotMatch = value;
    }

    /**
     * Gets the value of the totalMessagesExamined property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalMessagesExamined() {
        return totalMessagesExamined;
    }

    /**
     * Sets the value of the totalMessagesExamined property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalMessagesExamined(BigInteger value) {
        this.totalMessagesExamined = value;
    }

}
