//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.10.25 at 09:51:33 AM EDT 
//


package com.solacesystems.semp_jaxb.r9_2_0VMR.reply;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for smrpPacketTypeStats complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="smrpPacketTypeStats"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="packets-rx" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="bytes-rx" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="packets-tx" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="bytes-tx" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "smrpPacketTypeStats", propOrder = {

})
public class SmrpPacketTypeStats {

    @XmlElement(name = "packets-rx")
    protected long packetsRx;
    @XmlElement(name = "bytes-rx")
    protected long bytesRx;
    @XmlElement(name = "packets-tx")
    protected long packetsTx;
    @XmlElement(name = "bytes-tx")
    protected long bytesTx;

    /**
     * Gets the value of the packetsRx property.
     * 
     */
    public long getPacketsRx() {
        return packetsRx;
    }

    /**
     * Sets the value of the packetsRx property.
     * 
     */
    public void setPacketsRx(long value) {
        this.packetsRx = value;
    }

    /**
     * Gets the value of the bytesRx property.
     * 
     */
    public long getBytesRx() {
        return bytesRx;
    }

    /**
     * Sets the value of the bytesRx property.
     * 
     */
    public void setBytesRx(long value) {
        this.bytesRx = value;
    }

    /**
     * Gets the value of the packetsTx property.
     * 
     */
    public long getPacketsTx() {
        return packetsTx;
    }

    /**
     * Sets the value of the packetsTx property.
     * 
     */
    public void setPacketsTx(long value) {
        this.packetsTx = value;
    }

    /**
     * Gets the value of the bytesTx property.
     * 
     */
    public long getBytesTx() {
        return bytesTx;
    }

    /**
     * Sets the value of the bytesTx property.
     * 
     */
    public void setBytesTx(long value) {
        this.bytesTx = value;
    }

}
