//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.10.25 at 09:51:33 AM EDT 
//


package com.solacesystems.semp_jaxb.r9_2_0VMR.reply;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for spooled-message complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="spooled-message"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="message-id" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/&gt;
 *         &lt;element name="priority" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *           &lt;element name="date-seconds" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *           &lt;element name="publisher-id" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *           &lt;element name="sequence-number" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *           &lt;element name="expiry-time" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *           &lt;element name="expiry-time-seconds" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *           &lt;element name="dead-message-queue-eligible" type="{}yes-no-type"/&gt;
 *           &lt;element name="content-size" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *           &lt;element name="content-size-bytes" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/&gt;
 *           &lt;element name="attachment-size" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *           &lt;element name="attachment-size-bytes" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/&gt;
 *           &lt;element name="replicated"&gt;
 *             &lt;simpleType&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                 &lt;enumeration value="yes"/&gt;
 *                 &lt;enumeration value="no"/&gt;
 *                 &lt;enumeration value="pending"/&gt;
 *                 &lt;enumeration value="unknown"/&gt;
 *               &lt;/restriction&gt;
 *             &lt;/simpleType&gt;
 *           &lt;/element&gt;
 *           &lt;element name="replicated-mate-message-id" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *           &lt;element name="message-sent" type="{}yes-no-type"/&gt;
 *           &lt;element name="redeliveries" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "spooled-message", propOrder = {
    "messageId",
    "priority",
    "dateOrDateSecondsOrPublisherId"
})
public class SpooledMessage {

    @XmlElement(name = "message-id", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger messageId;
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger priority;
    @XmlElementRefs({
        @XmlElementRef(name = "date", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "date-seconds", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "publisher-id", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "sequence-number", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "expiry-time", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "expiry-time-seconds", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "dead-message-queue-eligible", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "content-size", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "content-size-bytes", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "attachment-size", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "attachment-size-bytes", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "replicated", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "replicated-mate-message-id", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "message-sent", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "redeliveries", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> dateOrDateSecondsOrPublisherId;

    /**
     * Gets the value of the messageId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMessageId() {
        return messageId;
    }

    /**
     * Sets the value of the messageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMessageId(BigInteger value) {
        this.messageId = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPriority(BigInteger value) {
        this.priority = value;
    }

    /**
     * Gets the value of the dateOrDateSecondsOrPublisherId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dateOrDateSecondsOrPublisherId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDateOrDateSecondsOrPublisherId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link Long }{@code >}
     * {@link JAXBElement }{@code <}{@link Long }{@code >}
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Double }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link Double }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Long }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getDateOrDateSecondsOrPublisherId() {
        if (dateOrDateSecondsOrPublisherId == null) {
            dateOrDateSecondsOrPublisherId = new ArrayList<JAXBElement<?>>();
        }
        return this.dateOrDateSecondsOrPublisherId;
    }

}
