//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.10.25 at 09:51:33 AM EDT 
//


package com.solacesystems.semp_jaxb.r9_2_0VMR.reply;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tcp complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tcp"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="mss" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *         &lt;element name="initial-congestion-window" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *         &lt;element name="maximum-tcp-window-size-in-KB" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *         &lt;element name="keepalive" type="{}keepalive" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tcp", propOrder = {

})
public class Tcp {

    @XmlSchemaType(name = "unsignedInt")
    protected Long mss;
    @XmlElement(name = "initial-congestion-window")
    @XmlSchemaType(name = "unsignedInt")
    protected Long initialCongestionWindow;
    @XmlElement(name = "maximum-tcp-window-size-in-KB")
    @XmlSchemaType(name = "unsignedInt")
    protected Long maximumTcpWindowSizeInKB;
    protected Keepalive keepalive;

    /**
     * Gets the value of the mss property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMss() {
        return mss;
    }

    /**
     * Sets the value of the mss property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMss(Long value) {
        this.mss = value;
    }

    /**
     * Gets the value of the initialCongestionWindow property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getInitialCongestionWindow() {
        return initialCongestionWindow;
    }

    /**
     * Sets the value of the initialCongestionWindow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setInitialCongestionWindow(Long value) {
        this.initialCongestionWindow = value;
    }

    /**
     * Gets the value of the maximumTcpWindowSizeInKB property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMaximumTcpWindowSizeInKB() {
        return maximumTcpWindowSizeInKB;
    }

    /**
     * Sets the value of the maximumTcpWindowSizeInKB property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMaximumTcpWindowSizeInKB(Long value) {
        this.maximumTcpWindowSizeInKB = value;
    }

    /**
     * Gets the value of the keepalive property.
     * 
     * @return
     *     possible object is
     *     {@link Keepalive }
     *     
     */
    public Keepalive getKeepalive() {
        return keepalive;
    }

    /**
     * Sets the value of the keepalive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Keepalive }
     *     
     */
    public void setKeepalive(Keepalive value) {
        this.keepalive = value;
    }

}
