//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.10.25 at 09:51:33 AM EDT 
//


package com.solacesystems.semp_jaxb.r9_2_0VMR.reply;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for uptime-type complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="uptime-type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="days" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="hours" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="mins" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="secs" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="total-secs" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "uptime-type", propOrder = {

})
public class UptimeType {

    protected int days;
    protected int hours;
    protected int mins;
    protected int secs;
    @XmlElement(name = "total-secs")
    @XmlSchemaType(name = "unsignedInt")
    protected Long totalSecs;

    /**
     * Gets the value of the days property.
     * 
     */
    public int getDays() {
        return days;
    }

    /**
     * Sets the value of the days property.
     * 
     */
    public void setDays(int value) {
        this.days = value;
    }

    /**
     * Gets the value of the hours property.
     * 
     */
    public int getHours() {
        return hours;
    }

    /**
     * Sets the value of the hours property.
     * 
     */
    public void setHours(int value) {
        this.hours = value;
    }

    /**
     * Gets the value of the mins property.
     * 
     */
    public int getMins() {
        return mins;
    }

    /**
     * Sets the value of the mins property.
     * 
     */
    public void setMins(int value) {
        this.mins = value;
    }

    /**
     * Gets the value of the secs property.
     * 
     */
    public int getSecs() {
        return secs;
    }

    /**
     * Sets the value of the secs property.
     * 
     */
    public void setSecs(int value) {
        this.secs = value;
    }

    /**
     * Gets the value of the totalSecs property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTotalSecs() {
        return totalSecs;
    }

    /**
     * Sets the value of the totalSecs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTotalSecs(Long value) {
        this.totalSecs = value;
    }

}
