//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.10.25 at 09:51:33 AM EDT 
//


package com.solacesystems.semp_jaxb.r9_2_0VMR.reply;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for vrfRoutesType complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="vrfRoutesType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="vrf-name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="num-static-routes" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/&gt;
 *         &lt;element name="route-infos"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="route-info" type="{}routeEntryType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="num-config-static-routes" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/&gt;
 *         &lt;element name="config-route-infos" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="route-info" type="{}routeEntryType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="interface-route-infos" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="route-info" type="{}routeEntryType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vrfRoutesType", propOrder = {

})
public class VrfRoutesType {

    @XmlElement(name = "vrf-name", required = true)
    protected String vrfName;
    @XmlElement(name = "num-static-routes")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger numStaticRoutes;
    @XmlElement(name = "route-infos", required = true)
    protected VrfRoutesType.RouteInfos routeInfos;
    @XmlElement(name = "num-config-static-routes")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger numConfigStaticRoutes;
    @XmlElement(name = "config-route-infos")
    protected VrfRoutesType.ConfigRouteInfos configRouteInfos;
    @XmlElement(name = "interface-route-infos")
    protected VrfRoutesType.InterfaceRouteInfos interfaceRouteInfos;

    /**
     * Gets the value of the vrfName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVrfName() {
        return vrfName;
    }

    /**
     * Sets the value of the vrfName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVrfName(String value) {
        this.vrfName = value;
    }

    /**
     * Gets the value of the numStaticRoutes property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumStaticRoutes() {
        return numStaticRoutes;
    }

    /**
     * Sets the value of the numStaticRoutes property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumStaticRoutes(BigInteger value) {
        this.numStaticRoutes = value;
    }

    /**
     * Gets the value of the routeInfos property.
     * 
     * @return
     *     possible object is
     *     {@link VrfRoutesType.RouteInfos }
     *     
     */
    public VrfRoutesType.RouteInfos getRouteInfos() {
        return routeInfos;
    }

    /**
     * Sets the value of the routeInfos property.
     * 
     * @param value
     *     allowed object is
     *     {@link VrfRoutesType.RouteInfos }
     *     
     */
    public void setRouteInfos(VrfRoutesType.RouteInfos value) {
        this.routeInfos = value;
    }

    /**
     * Gets the value of the numConfigStaticRoutes property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumConfigStaticRoutes() {
        return numConfigStaticRoutes;
    }

    /**
     * Sets the value of the numConfigStaticRoutes property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumConfigStaticRoutes(BigInteger value) {
        this.numConfigStaticRoutes = value;
    }

    /**
     * Gets the value of the configRouteInfos property.
     * 
     * @return
     *     possible object is
     *     {@link VrfRoutesType.ConfigRouteInfos }
     *     
     */
    public VrfRoutesType.ConfigRouteInfos getConfigRouteInfos() {
        return configRouteInfos;
    }

    /**
     * Sets the value of the configRouteInfos property.
     * 
     * @param value
     *     allowed object is
     *     {@link VrfRoutesType.ConfigRouteInfos }
     *     
     */
    public void setConfigRouteInfos(VrfRoutesType.ConfigRouteInfos value) {
        this.configRouteInfos = value;
    }

    /**
     * Gets the value of the interfaceRouteInfos property.
     * 
     * @return
     *     possible object is
     *     {@link VrfRoutesType.InterfaceRouteInfos }
     *     
     */
    public VrfRoutesType.InterfaceRouteInfos getInterfaceRouteInfos() {
        return interfaceRouteInfos;
    }

    /**
     * Sets the value of the interfaceRouteInfos property.
     * 
     * @param value
     *     allowed object is
     *     {@link VrfRoutesType.InterfaceRouteInfos }
     *     
     */
    public void setInterfaceRouteInfos(VrfRoutesType.InterfaceRouteInfos value) {
        this.interfaceRouteInfos = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="route-info" type="{}routeEntryType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "routeInfo"
    })
    public static class ConfigRouteInfos {

        @XmlElement(name = "route-info")
        protected List<RouteEntryType> routeInfo;

        /**
         * Gets the value of the routeInfo property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the routeInfo property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRouteInfo().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RouteEntryType }
         * 
         * 
         */
        public List<RouteEntryType> getRouteInfo() {
            if (routeInfo == null) {
                routeInfo = new ArrayList<RouteEntryType>();
            }
            return this.routeInfo;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="route-info" type="{}routeEntryType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "routeInfo"
    })
    public static class InterfaceRouteInfos {

        @XmlElement(name = "route-info")
        protected List<RouteEntryType> routeInfo;

        /**
         * Gets the value of the routeInfo property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the routeInfo property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRouteInfo().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RouteEntryType }
         * 
         * 
         */
        public List<RouteEntryType> getRouteInfo() {
            if (routeInfo == null) {
                routeInfo = new ArrayList<RouteEntryType>();
            }
            return this.routeInfo;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="route-info" type="{}routeEntryType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "routeInfo"
    })
    public static class RouteInfos {

        @XmlElement(name = "route-info")
        protected List<RouteEntryType> routeInfo;

        /**
         * Gets the value of the routeInfo property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the routeInfo property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRouteInfo().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RouteEntryType }
         * 
         * 
         */
        public List<RouteEntryType> getRouteInfo() {
            if (routeInfo == null) {
                routeInfo = new ArrayList<RouteEntryType>();
            }
            return this.routeInfo;
        }

    }

}
