//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.10.25 at 09:51:33 AM EDT 
//


package com.solacesystems.semp_jaxb.r9_2_0VMR.reply;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for webTransportTypeStats complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="webTransportTypeStats"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="web-transport-msgs-rcvd" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="web-transport-msgs-sent" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="web-transport-bytes-rcvd" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="web-transport-bytes-sent" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="tcp-received-out-of-order-rcvd" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="tcp-fast-retransmit-sent" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="tcp-timed-retransmit-sent" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="web-transport-session-id-invalid-rcvd" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "webTransportTypeStats", propOrder = {

})
public class WebTransportTypeStats {

    @XmlElement(name = "web-transport-msgs-rcvd")
    protected long webTransportMsgsRcvd;
    @XmlElement(name = "web-transport-msgs-sent")
    protected long webTransportMsgsSent;
    @XmlElement(name = "web-transport-bytes-rcvd")
    protected long webTransportBytesRcvd;
    @XmlElement(name = "web-transport-bytes-sent")
    protected long webTransportBytesSent;
    @XmlElement(name = "tcp-received-out-of-order-rcvd")
    protected long tcpReceivedOutOfOrderRcvd;
    @XmlElement(name = "tcp-fast-retransmit-sent")
    protected long tcpFastRetransmitSent;
    @XmlElement(name = "tcp-timed-retransmit-sent")
    protected long tcpTimedRetransmitSent;
    @XmlElement(name = "web-transport-session-id-invalid-rcvd")
    protected Long webTransportSessionIdInvalidRcvd;

    /**
     * Gets the value of the webTransportMsgsRcvd property.
     * 
     */
    public long getWebTransportMsgsRcvd() {
        return webTransportMsgsRcvd;
    }

    /**
     * Sets the value of the webTransportMsgsRcvd property.
     * 
     */
    public void setWebTransportMsgsRcvd(long value) {
        this.webTransportMsgsRcvd = value;
    }

    /**
     * Gets the value of the webTransportMsgsSent property.
     * 
     */
    public long getWebTransportMsgsSent() {
        return webTransportMsgsSent;
    }

    /**
     * Sets the value of the webTransportMsgsSent property.
     * 
     */
    public void setWebTransportMsgsSent(long value) {
        this.webTransportMsgsSent = value;
    }

    /**
     * Gets the value of the webTransportBytesRcvd property.
     * 
     */
    public long getWebTransportBytesRcvd() {
        return webTransportBytesRcvd;
    }

    /**
     * Sets the value of the webTransportBytesRcvd property.
     * 
     */
    public void setWebTransportBytesRcvd(long value) {
        this.webTransportBytesRcvd = value;
    }

    /**
     * Gets the value of the webTransportBytesSent property.
     * 
     */
    public long getWebTransportBytesSent() {
        return webTransportBytesSent;
    }

    /**
     * Sets the value of the webTransportBytesSent property.
     * 
     */
    public void setWebTransportBytesSent(long value) {
        this.webTransportBytesSent = value;
    }

    /**
     * Gets the value of the tcpReceivedOutOfOrderRcvd property.
     * 
     */
    public long getTcpReceivedOutOfOrderRcvd() {
        return tcpReceivedOutOfOrderRcvd;
    }

    /**
     * Sets the value of the tcpReceivedOutOfOrderRcvd property.
     * 
     */
    public void setTcpReceivedOutOfOrderRcvd(long value) {
        this.tcpReceivedOutOfOrderRcvd = value;
    }

    /**
     * Gets the value of the tcpFastRetransmitSent property.
     * 
     */
    public long getTcpFastRetransmitSent() {
        return tcpFastRetransmitSent;
    }

    /**
     * Sets the value of the tcpFastRetransmitSent property.
     * 
     */
    public void setTcpFastRetransmitSent(long value) {
        this.tcpFastRetransmitSent = value;
    }

    /**
     * Gets the value of the tcpTimedRetransmitSent property.
     * 
     */
    public long getTcpTimedRetransmitSent() {
        return tcpTimedRetransmitSent;
    }

    /**
     * Sets the value of the tcpTimedRetransmitSent property.
     * 
     */
    public void setTcpTimedRetransmitSent(long value) {
        this.tcpTimedRetransmitSent = value;
    }

    /**
     * Gets the value of the webTransportSessionIdInvalidRcvd property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getWebTransportSessionIdInvalidRcvd() {
        return webTransportSessionIdInvalidRcvd;
    }

    /**
     * Sets the value of the webTransportSessionIdInvalidRcvd property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setWebTransportSessionIdInvalidRcvd(Long value) {
        this.webTransportSessionIdInvalidRcvd = value;
    }

}
