//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1-b171012.0423 
//         See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2019.10.25 at 09:51:26 AM EDT 
//


package com.solacesystems.semp_jaxb.r9_2_0VMR.request;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MSG_VPN_AUTHN_CLIENT_CERT_USERNAME_SOURCE_PARAM.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MSG_VPN_AUTHN_CLIENT_CERT_USERNAME_SOURCE_PARAM"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="common-name"/&gt;
 *     &lt;enumeration value="subject-alternate-name-msupn"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "MSG_VPN_AUTHN_CLIENT_CERT_USERNAME_SOURCE_PARAM")
@XmlEnum
public enum MSGVPNAUTHNCLIENTCERTUSERNAMESOURCEPARAM {

    @XmlEnumValue("common-name")
    COMMON_NAME("common-name"),
    @XmlEnumValue("subject-alternate-name-msupn")
    SUBJECT_ALTERNATE_NAME_MSUPN("subject-alternate-name-msupn");
    private final String value;

    MSGVPNAUTHNCLIENTCERTUSERNAMESOURCEPARAM(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MSGVPNAUTHNCLIENTCERTUSERNAMESOURCEPARAM fromValue(String v) {
        for (MSGVPNAUTHNCLIENTCERTUSERNAMESOURCEPARAM c: MSGVPNAUTHNCLIENTCERTUSERNAMESOURCEPARAM.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
